import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import React from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-white shadow p-4 flex gap-4">
          <Link href="/" className="text-blue-600 hover:underline">Home</Link>
          <Link href="/about" className="text-blue-600 hover:underline">About</Link>
          <Link href="/routes" className="text-blue-600 hover:underline">Tour Routes</Link>
          <Link href="/contact" className="text-blue-600 hover:underline">Contact</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}